[package]
name = "rari-md"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
base64 = "0.22"
regex = "1"
once_cell = "1"
thiserror = "1"
comrak = { version = "0.24", default-features = false, features = ["syntect"] }
rari-types = { path = "../rari-types" }
itertools = "0.13"
