on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          repo-url: mdn/rari
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
